### ISSUE TITLE
Beispiele fehlen

### ISSUE THREAD

**Issue by JBlond** [UweZiegenhagen/golem-public#1]
Die in https://www.golem.de/news/latex-schreibst-du-noch-oder-setzt-du-schon-2201-162303-2.html referenzierten Beispiele fehlen

**Comment by ghost** [comment]
Habe mich darum gekümmert und einen Pullrequest eröffnet.

**Comment by UweZiegenhagen** [comment]
Sind jetzt vorhanden.
