### ISSUE TITLE
XeLatex: There is no ^^K in font...

### ISSUE THREAD

**Issue by loh-tar** [UweZiegenhagen/golem-public#4]
Hallo Uwe,
ich versuche von TeXLive weg zu kommen und stolpere über diese Warnungen. Zum Glück tauchen die genau so auch mit Deinem Beispiel auf, und nicht nur mit meinen alten Vorlagen. Ich suchte mir im Netz schon einen Wolf. Vergeblich.

```
$ miktex-xelatex Brief-02.tex 
<schnipp>
Missing character: There is no ^^K in font [lmsans8-regular]:mapping=tex-text;!
Missing character: There is no ^^K in font [lmroman12-regular]:mapping=tex-text
<schnapp>
```

```
$ tectonic Brief-02.tex
<schnipp>
tectonic Brief-02.tex
warning: Brief-02.tex:13: Missing character: There is no ^^K in font [lmsans8-regular]:mapping=tex-text;!
warning: could not represent character "
                                        " (0xb) in font "[lmsans8-regular]:mapping=tex-text;"
warning:   you may need to load the `fontspec` package and use (e.g.) \setmainfont to
warning:   choose a different font that covers the unrepresentable character(s)
<schnapp>
```

Das erzeugte PDF sieht tadellos aus, aber die Warnungen sind schon sehr irritierend. Mit _miktex-pdflatex_ geht es natürlich ohne Gemecker, aber ich würde gerne auf _tectonic_ umsteigen.

Brief-01.tex geht auch ohne Warnungen. 

Benötigt Koma-Script evtl einen besonderen XeLaTex Schalter? Oder ist das ein Fehler bei den?

Dank und Gruß, Lothar

PS: Bin kompletter TeX-Noob. Ich bitte das bei einer Antwort berücksichtigen ;-)

**Comment by UweZiegenhagen** [comment]
Schau ich mir an.

**Comment by UweZiegenhagen** [comment]
U+000B ist der vertikale Tabulator und ich habe keine Ahnung, wo im Dokument dieser gesetzt wird. Ist vermutlich einer der vertikalen Abstände. Mit pdflatex kommt die Fehlermeldung nicht. Vermutlich ist es besser, bei Nutzung von xelatex und lualatex eine der Systemschriftarten zu nutzen. Wie das geht zeige ich im nächsten Artikel.

**Comment by loh-tar** [comment]
Danke für deine Bemühungen, bin gespannt auf den Artikel.
